###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    postgres:
        image: 'postgres:12'
        working_dir: /application
        volumes:
            - '.:/application'
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=j1mGD
            - POSTGRES_DB=devdb
        
        ports:
            - '63001:5432'

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '63000:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
